name: found
favicon: null
layout_spectrum: 0.4203277723863721
typography_spectrum: 0.3471509045921266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#939597'
    - '#00baf2'
    - '#137191'
    - '#000000'
    - '#004080'
  brandStrength: 0.5
  lightness: 0.9749721062835306
  saturation: 0.535761367995292
  rhythmicContrast: 0.864937542937696
purpose: []
